version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  verbosity: minimal
  artifacts:
- path: /
  name: XGile2
  type: WebDeployPackage
deploy:
  - provider: Environment
    name: XGile2
    on:
       branch: master
